package main

var foxmosaStickerMap = map[string]string{
  "BQADBQADhwADMqsKAuEXXyu4ilLCAg": "celebrate",
  "BQADBQADogADMqsKAiykgKeu_QqfAg": "busy bee",
  "BQADBQADpAADMqsKAvrSFOHsu44HAg": "enthusiast",
  "BQADBQADpgADMqsKAuYN0dN0aGTUAg": "evergreen",
  "BQADBQADqAADMqsKAvnjyOmGak8JAg": "middle manager",
  "BQADBQADqgADMqsKAruaTkuu2qMjAg": "stalwart",
  "BQADBQADrAADMqsKAsOBf5BSdIygAg": "wizard",
  "BQADBQADrgADMqsKAk-8VDZI5syBAg": "happy",
  "BQADBQADsAADMqsKAsjoJq9W1mnJAg": "angry",
  "BQADBQADsgADMqsKAn1ZJzgWzhXWAg": ">_<",
  "BQADBQADtAADMqsKAlqjbFYO-FLnAg": "earth",
  "BQADBQADtgADMqsKAm9Aq8_sQD4CAg": "cry",
  "BQADBQADuAADMqsKApqwMzGgHOG_Ag": "cold",
  "BQADBQADugADMqsKAn1kX4dPws_CAg": "hot",
  "BQADBQADvAADMqsKAgb5xjXJjzyvAg": "hello",
  "BQADBQADvgADMqsKAnNrrR6SuUN5Ag": "thank you",
  "BQADBQADwAADMqsKApo_afe6O3GoAg": "sorry",
  "BQADBQADwgADMqsKAoyU0Rf8ennsAg": "yes",
  "BQADBQADxAADMqsKAu9Fj-Hk2TYeAg": "no",
  "BQADBQADxgADMqsKAr-MVAGFIIN6Ag": "talk",
  "BQADBQADyAADMqsKAhQTwocHyOQ_Ag": "ok",
  "BQADBQADygADMqsKAjO6gRJuUsPqAg": "bye",
  "BQADBQADzAADMqsKAg2qubqB-4z4Ag": "idea",
  "BQADBQADTgADMqsKAl9An_1enGbDAg": "goodbye",
  "BQADBQADzgADMqsKAnjUAwwE5nf8Ag": "laugh",
  "BQADBQAD0AADMqsKAkT-uRm0P1jmAg": "zzz",
  "BQADBQAD0gADMqsKArq7YTph4p5aAg": "surprise",
  "BQADBQAD1AADMqsKAmKuPRXjbh1aAg": "...",
  "BQADBQAD1gADMqsKAuUvKVdRaw-qAg": "!",
  "BQADBQAD2AADMqsKApeWEBYFs7BjAg": "?",
  "BQADBQAD2gADMqsKApTXhSGYWxSmAg": "murmur",
  "BQADBQAD3AADMqsKAo-VQAq_8HYXAg": "shy",
  "BQADBQAD3gADMqsKArUFvcZdDhA7Ag": "dont cry",
  "BQADBQAD4AADMqsKAiE-VLGdmtsfAg": "ballon",
  "BQADBQAD4gADMqsKAmMxkBZLkxsyAg": "reading",
  "BQADBQAD5AADMqsKAgkmreZlv1wOAg": "run",
  "BQADBQAD5gADMqsKAmcgPxorJvMAAQI": "love",
  "BQADBQAD6AADMqsKArOT7I0H_tA8Ag": "mozilla",
  "BQADBQAD6gADMqsKAroeYhRggGEHAg": "search",
  "BQADBQAD7AADMqsKAhD8DBFd9GSOAg": "morning",
  "BQADBQAD7gADMqsKAocv8RTuppDsAg": "night",
  "BQADBQAD8AADMqsKAuImFfNs4MSeAg": "treasure",
  "BQADBQAD8gADMqsKAnRwt5734TJxAg": "jump",
  "BQADBQAD9AADMqsKAgumiO4jzV3sAg": "rain",
  "BQADBQAD9gADMqsKAr-cnBtx7EhLAg": "tasty",
  "BQADBQAD-AADMqsKAosqIG_cPwWEAg": "rabbit",
  "BQADBQAD-gADMqsKAowZ-jtjlIwlAg": "merry christmas",
  "BQADBQAD_AADMqsKAhpC1bPhIdi_Ag": "happy new year",
}
